on:
  push:
    branches:
      - main
      - development

jobs:
  set_environment:
    runs-on: ubuntu-latest
    steps:
      # ... your existing steps ...

  Folder_selection:
    runs-on: ubuntu-latest
    needs: set_environment
    steps:
      # ... your existing steps ...

  Lamda_DEPLOY:
    runs-on: ubuntu-latest
    needs:
      - set_environment
      - Folder_selection
    environment: ${{ needs.set_environment.outputs.environment }}
    env:
      STAGE: ${{ secrets.STAGE }}
    steps:
      - name: Execute commands based on folder name -notfication
        if: needs.Folder_selection.outputs.lavanya  == 'true'
        run: |
          echo "npx serverless mono --app lavanya --command 'deploy --stage $STAGE'"
     
      - name: Execute commands based on folder name -report
        if: needs.Folder_selection.outputs.pavi  == 'true'
        run: |
          echo "npx serverless mono --app pavi --command 'deploy --stage $STAGE'"
     
      - name: Execute commands based on folder name -libs
        if: steps.Folder_selection.outputs.confd == 'true'
        run: |
          AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
          apps=("lavanya" "pavi")
          for app in "${apps[@]}"; do
            echo "$app"
          done
          
          
          
          
