name: first pipeline

on:
  push:
    branches:
      - main

jobs:
  DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract Changed Folder
        id: extract_folder
        run: |
          # Get the changed files from the commit range
          CHANGED_FILES=$(git diff --name-only "${{ github.event.before }}" "${{ github.sha }}")
  
          # Extract the folder name from the changed file paths and store in an array
          CHANGED_FOLDERS=($(echo "${CHANGED_FILES}" | grep -o 'myapp/[^/]*' | sort -u))
  
          # Join the array elements with comma to form a comma-separated string
          CHANGED_FOLDER_LIST=$(IFS=','; echo "${CHANGED_FOLDERS[*]}")
  
          echo "Changed folder(s): $CHANGED_FOLDER_LIST" >> $GITHUB_ENV

      - name: Execute commands based on folder name
        run: |
          for folder in $(echo "${{ env.CHANGED_FOLDER_LIST }}" | tr "," "\n"); do
            echo "Processing folder: $folder"
            npx serverless mono --app $folder --command "deploy --stage production" # Replace 'production' with the appropriate stage
          done
