on:
  push:
    branches:

      - main

jobs:

 set_environment:

     runs-on: ubuntu-latest
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: folder selection
       uses: dorny/paths-filter@v2
       id: changes
       with:
           filters: |
              lavanya:
                - 'myapp/lavanya**'
              pavi:
                - 'myapp/pavi**'
              
          
     - name: Execute commands based on folder name -notfication
       if: steps.changes.outputs.lavanya == 'true'
       run: |
         npx serverless mono --app lavanya --command 'deploy --stage $STAGE'
     
     - name: Execute commands based on folder name -report
       if: steps.changes.outputs.pavi == 'true'
       run: |
         echo "npx serverless mono --app pavi --command"
     
    
