on:
  push:
    branches:

      - main

jobs:

 set_environment:

     runs-on: ubuntu-latest
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: folder selection
       uses: dorny/paths-filter@v2
       id: changes
       with:
           filters: |
              notfication:
                - 'myapp/lavanya**'
              report:
                - 'myapp/pavi**'
              merchant-settings:
                - 'src/apps/merchant-settings/**'
          
     - name: Execute commands based on folder name -notfication
       if: steps.changes.outputs.notfication == 'true'
       run: |
         npx serverless mono --app notification --command 'deploy --stage $STAGE'
     
     - name: Execute commands based on folder name -report
       if: steps.changes.outputs.report == 'true'
       run: |
         echo "npx serverless mono --app report --command"
     - name: Execute commands based on folder name -notfication
       if: steps.changes.outputs.merchant-settings == 'true'
       run: |
         echo "npx serverless mono --app merchant-settings --command "

    
