name : first pipeline

on:
  push:
    branches:
      - main

jobs:
  DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract Changed Folder
        id: extract_folder
        run: |
          
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
         
          CHANGED_FOLDERS=($(echo "${CHANGED_FILES}" | grep -o 'src/apps/[^/]*' | sort -u))

          CHANGED_FOLDER_LIST=$(IFS=','; echo "${CHANGED_FOLDERS[*]}")

          echo "Changed folder(s): $CHANGED_FOLDER_LIST" >> $GITHUB_ENV

      - name: Execute commands based on folder name
        run: |
          for folder in $(echo $CHANGED_FOLDER_LIST | tr "," "\n"); do
            echo "Processing folder: $folder"
            npx serverless mono --app $folder --command "deploy --stage $STAGE"
          done
