name: Create Freshservice Ticket

on:
  push:
    branches:
      - main

jobs:
  create_ticket:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        id: env
        run: |
          echo "summary=${{ github.event.head_commit.message }}" >> $GITHUB_ENV
          echo "description=Ticket description goes here" >> $GITHUB_ENV
          echo "priority=1" >> $GITHUB_ENV
          echo "status=2" >> $GITHUB_ENV

      - name: Create ticket in Freshservice
        env:
          FRESHSERVICE_API_KEY: ${{ secrets.FRESHSERVICE_API_KEY }}
          FRESHSERVICE_SUBDOMAIN: senguntharengineeringcollehelpdesk
          SUMMARY: ${{ env.summary }}
          DESCRIPTION: ${{ env.description }}
          PRIORITY: ${{ env.priority }}
          STATUS: ${{ env.status }}
        run: |
          FRESHSERVICE_API_URL="https://senguntharengineeringcollehelpdesk.freshservice.com/"
          echo "---------------------------------"
          curl -X POST $FRESHSERVICE_API_URL \
            -H "Content-Type: application/json" \
            -H "Authorization: Basic $FRESHSERVICE_API_KEY" \
            -d '{
              "helpdesk_ticket": {
                "description": "'"$DESCRIPTION"'",
                "subject": "'"$SUMMARY"'",
                "priority": '$PRIORITY',
                "status": '$STATUS'
              }
            }'
