on:
  push:
    branches:
      - main
      - prod
   
jobs:
  Checkout:
    runs-on: ubuntu-latest
    outputs :
          build_status: ${{ job.status }}
    steps :
      - name: Checkout repository
        uses: actions/checkout@v2  
      - name : sdf
        run : echo "hello"
  validate :
       runs-on: ubuntu-latest
       outputs :
          build_status: ${{ job.status }} 
       steps :
         - name: Checkout repository
           uses: actions/checkout@v2  
         - name : sdfsdf
           run : echo "hellosdfg"
  lavanya:
     runs-on: ubuntu-latest
     if : always ()
     needs :
        - Checkout
        - validate
     steps :
        - name: Checkout repository
          uses: actions/checkout@v2 
          
        - name : sdfgn
          if: ${{ needs.Checkout.outputs.build_status == 'failure' || needs.validate.outputs.build_status == 'failure' }}
          run: |
           echo"
                     SUBJECT: "GitHub Actions Build: ${{ github.repository }} ${{ github.job }} is ${{ job.status }}"
                     MESSAGE: |
                                                              "Build Status: ${{ job.status }}"
                             "Job: ${{ github.run_id }}"
                        "Build Number: ${{ github.run_number }}"
                             "Repository: ${{ github.repository }}"
                              "Repository Owner: ${{ github.repository_owner }}"
                        "Default Branch: ${{ github.head_ref }}"
                       "Workflow: ${{ github.workflow }}"
                              "Event Type: ${{ github.event_name }}"
                            "Triggered By: ${{ github.actor }}"
                             "Source IP: ${{ github.event.client_ip }}"
                                   "Commit SHA: ${{ github.sha }}"
                            "Commit Message: ${{ github.event.head_commit.message }}"
                          "More info at: https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks""
        - name: AWS Publish notifications FOR SUCCESS
          if: ${{ needs.Checkout.outputs.build_status == 'success' || needs.validate.outputs.build_status == 'success' }}
          run :
                   |
                   echo  "
                       SUBJECT: "GitHub Actions Build: ${{ github.repository }} ${{ github.job }} is ${{ job.status }}"
                       MESSAGE: |
                      "Build Status: ${{ job.status }}"
                    "Job: ${{ github.run_id }}"
                     "Build Number: ${{ github.run_number }}"
                        "Repository: ${{ github.repository }}"
                         "Workflow: ${{ github.workflow }}"
                           "Event Type: ${{ github.event_name }}"
                          "Triggered By: ${{ github.actor }}"
                          "Source IP: ${{ github.event.client_ip }}"
                           "Commit SHA: ${{ github.sha }}"
                              "Commit Message: ${{ github.event.head_commit.message }}"
                              "Start Time: ${{ github.run_started_at }}"
                               "End Time: ${{ github.run_completed_at }}"
                               "Time Taken: ${{ steps.build_time.outputs.time_taken }}"
                               "Deployment Status: ${{ needs.DEV-DEPLOY.outputs.deployment_status }}"
                                   "Deployment Target: DEV"
                                    "Deployment Time: ${{ needs.DEV-DEPLOY.outputs.deployment_time }}"
                                "More info at: https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks"

      
