name: Create Freshservice Ticket

on:
  push:
    branches:
      - main

jobs:
  create_ticket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Input ticket details
        id: input_ticket_details
        run: |
          echo "::set-output name=summary::${{ github.event.head_commit.message }}"
          echo "::set-output name=description::Ticket description goes here"
          echo "::set-output name=priority::1"
          echo "::set-output name=status::2"

      - name: Create ticket in Freshservice
        env:
          FRESHSERVICE_API_KEY: ${{ secrets.FRESHSERVICE_API_KEY }}
          FRESHSERVICE_SUBDOMAIN: senguntharengineeringcollehelpdesk
        run: |
          FRESHSERVICE_API_URL="https://senguntharengineeringcollehelpdesk.freshservice.com/"
          echo "next setpppp"
          SUMMARY="${{ steps.input_ticket_details.outputs.summary }}"
          DESCRIPTION="${{ steps.input_ticket_details.outputs.description }}"
          PRIORITY="${{ steps.input_ticket_details.outputs.priority }}"
          STATUS="${{ steps.input_ticket_details.outputs.status }}"
          echo "---------------------------------"
          curl -X POST $FRESHSERVICE_API_URL \
            -H "Content-Type: application/json" \
            -H "Authorization: Basic $FRESHSERVICE_API_KEY" \
            -d '{
              "helpdesk_ticket": {
                "description": "'"$DESCRIPTION"'",
                "subject": "'"$SUMMARY"'",
                "priority": '$PRIORITY',
                "status": '$STATUS'
              }
            }'
