name: Create Freshservice Ticket
on:
  push:
    branches:
      - lavanya  # Replace with your main branch name
  # You can adjust the trigger as per your requirements

jobs:
  create_ticket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Create Freshservice Ticket
        env:
          FRESHSERVICE_API_KEY: ${{ secrets.FRESHSERVICE_API_KEY }}
          FRESHSERVICE_DOMAIN: senguntharengineeringcollehelpdesk
        run: |
          # Replace the following with your ticket details
          ticketData='{
            "helpdesk_ticket": {
              "description": "This is a test ticket created via GitHub Actions pipeline.",
              "subject": "GitHub Actions Ticket",
              "priority": 1,
              "status": 2
            }
          }'

          response=$(curl -X POST "https://senguntharengineeringcollehelpdesk.freshservice.com/" \
            -H "Content-Type: application/json" \
            -H "Authorization: Basic $(echo -n "${FRESHSERVICE_API_KEY}:x" | base64)" \
            -d "$ticketData")

          # Print the response (optional)
          echo "Ticket Creation Response: $response"
