name: Upload to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - dev
      - prod
   
jobs:
  Checkout:
    runs-on: ubuntu-latest
    environment: ${{ needs.environments.outputs.env_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  environments:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.set_environment.outputs.env_name }}
    steps :
      - name: Checkout repository
        uses: actions/checkout@v2  
      - name: Set environment name
        id: set_environment
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/dev' ]]; then
            echo "::set-output name=env_name::dev"
          elif [[ ${{ github.ref }} == 'refs/heads/prod' ]]; then
            echo "::set-output name=env_name::prod"
          else
            echo "environment is not specified"
      - name: Create ZIP file
        run: |
           cd ${{ github.workspace }}
           ls -l
           zip -r ${{ github.workspace }}/mobile-web.zip . -x ./README.md .git\*
      - name: Copy files to S3 (DEV)
        env:
            NAME: ${{ secrets.DEV_BUCKET_NAME }}
        run:  aws s3 cp ${{ github.workspace }}/mobile-web.zip s3://$BUCKET_NAME/${{ github.repository }}/${{ github.run_number }}/mobile-web.zip
