name: Upload to S3 and Invalidate CloudFront

on:
  push:
    branches:

      - dev
      - prod
jobs:

 set_environment:

     runs-on: ubuntu-latest
    
     steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine environment based on branch
        id: set_env
        run: |
          if [ "$GITHUB_REF" == "refs/heads/prod" ]; then
            echo "environment=prod" >> "$GITHUB_ENV"
          elif [ "$GITHUB_REF" == "refs/heads/dev" ]; then
            echo "environment=dev" >> "$GITHUB_ENV"
          fi
     outputs:
       environment: ${{ env.environment }}
    
 CloudFront_DEPLOY:
 
   runs-on: ubuntu-latest
   needs: set_environment  
   environment: ${{ needs.set_environment.outputs.environment }}
   env: 
           BUCKET: ${{ secrets.BUCKET_NAME }}
   
   steps:

      - name: Checkout repository
        uses: actions/checkout@v2
      - name : Deploy to cloudfront
        run: |
         echo $BUCKET
         echo ${{ needs.set_environment.outputs.environment }}
         echo "https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks"
      
