on:
  push:
    branches:
      - dev
      - prod
   
jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps :
      - name: Checkout repository
        uses: actions/checkout@v2  
      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-access-key-id: ${{ secrets.ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.SECRET_KEY }}
            aws-region: eu-west-1
  Copy_to_files :
      runs-on: ubuntu-latest
      steps:
      - name: Create ZIP file
        run: |
              cd ${{ github.workspace }}
              excluded_files=$(find . -type f \
                    ! -name 'README.md' \
                    -exec echo {} \;)
               echo "$excluded_files" > excluded_files.txt
               cd ${{ github.workspace }}/
               zip -r ${{ github.workspace }}/mobile-web.zip . -i . -x@excluded_files.txt README.md .gitignore
               ls -l
      - name: Copy files to S3 (DEV)
        if: ${{ github.ref == 'refs/heads/dev' }}
        run:  aws s3 cp ${{ github.workspace }}/mobile-web.zip s3://lprashola/${{ github.repository }}/${{ github.run_number }}/mobile-web.zip
                                                                   
      - name: Copy files to S3 (PROD)
        if: ${{ github.ref == 'refs/heads/prod' }}
        run:  aws s3 cp ${{ github.workspace }}/mobile-web.zip s3://lprashola-2/${{ github.repository }}/${{ github.run_number }}/mobile-web.zip
                                                                    
