name: Upload to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - dev
      - prod
   
jobs:
 DEV-DEPLOY:
   runs-on: ubuntu-latest
   if : ${{ github.ref }} == 'refs/heads/dev'
   environment: dev
   steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-access-key-id: ${{ secrets.ACCESS_KEY}}
            aws-secret-access-key: ${{ secrets.SECRET_KEY }}
            aws-region: eu-north-1
             
      - name: Set environment name
        id: set_environment
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/dev' ]]; then
           echo "::set-output name=env_name::dev"
          elif [[ ${{ github.ref }} == 'refs/heads/prod' ]]; then
            echo "::set-output name=env_name::prod" 
          else
            echo "environment is not specified"
          fi
      - name: Create ZIP file
        run: |
           cd ${{ github.workspace }}
           ls -l
           zip -r ${{ github.workspace }}/mobile-web.zip . -x ./README.md .git\*
      - name: Copy files to S3 (DEV)
        env:
            NAME: ${{ secrets.BUCKET_NAME }}
        run:  aws s3 sync ${{ github.workspace }}/mobile-web.zip s3://$NAME/${{ github.repository }}/${{ github.run_number }}/mobile-web.zip  --debug

 PROD-DEPLOY:
   runs-on: ubuntu-latest
   if : ${{ github.ref }} == 'refs/heads/prod'
   environment: prod
   steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-access-key-id: ${{ secrets.ACCESS_KEY}}
            aws-secret-access-key: ${{ secrets.SECRET_KEY }}
            aws-region: eu-north-1
             
      - name: Create ZIP file
        run: |
           cd ${{ github.workspace }}
           ls -l
           zip -r ${{ github.workspace }}/mobile-web.zip . -x ./README.md .git\*
      - name: Copy files to S3 (DEV)
        env:
            NAME: ${{ secrets.BUCKET_NAME }}
        run:  aws s3 sync ${{ github.workspace }}/mobile-web.zip s3://$NAME/${{ github.repository }}/${{ github.run_number }}/mobile-web.zip  --debug
