on:
  push:
    branches:
      - dev
      - prod
   
jobs:
  Checkout:
    runs-on: ubuntu-latest
    environment: dev
    steps :
      - name: Checkout repository
        uses: actions/checkout@v2  
      
      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-access-key-id: ${{ secrets.ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.SECRET_KEY }}
            aws-region: eu-west-1
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install awscli -y
      - name: Create ZIP file
        run: |
           cd ${{ github.workspace }}
           ls -l
           zip -r ${{ github.workspace }}/mobile-web.zip . -x ./README.md .git\*
      - name: Copy files to S3 (DEV)
        shell: bash
        env:
          BUCKET_NAME: ${{secrets.DEV_BUCKET_NAME}}
        run:  aws s3 cp ${{ github.workspace }}/mobile-web.zip s3://$BUCKET_NAME/${{ github.repository }}/${{ github.run_number }}/mobile-web.zip
                                                          



