name: Set Environment Variables

on:
  push:
    branches:
      - dev
      - prod

jobs:
 my-job:
   runs-on: ubuntu-latest
   environment: dev
  
   steps :
      - name: Set env to staging
        shell: bash
        env:
            NAME: ${{ secrets.DEV_BUCKET_NAME }}
        run: |
          echo "$NAME"   
      - name: Display environment variables
        run: |
          echo $ENVIRONMENT
          echo $BUCKET_NAME


