name: Set Environment Variables

on:
  push:
    branches:
      - dev
      - prod

jobs:
  set_environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set env to staging
        run: |
          echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          echo "BUCKET_NAME=${{ env.DEV_BUCKET_NAME }}" >> $GITHUB_ENV

      - name: Display environment variables
        run: |
          echo $ENVIRONMENT
          echo $BUCKET_NAME
