on:
  push:
    branches:
      - dev
      - prod
   
jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps :
      - name: Checkout repository
        uses: actions/checkout@v2  
      
      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-access-key-id: ${{ secrets.ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.SECRET_KEY }}
            aws-region: eu-west-1
            
      - name: Create ZIP file
        run: |
           cd ${{ github.workspace }}
           ls -l
           zip -r ${{ github.workspace }}/mobile-web.zip . -x ./README.md .git\*

               
      - name: Copy files to S3 (DEV)
        if: ${{ github.ref == 'refs/heads/dev' }}
        env:
         DEV_BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        run:  aws s3 cp ${{ github.workspace }}/mobile-web.zip s3://${{ env.DEV_BUCKET_NAME }}/${{ github.repository }}/${{ github.run_number }}/mobile-web.zip
                                                                   
      - name: Copy files to S3 (PROD)
        if: ${{ github.ref == 'refs/heads/prod' }}
        env : 
          PROD_BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        run:  aws s3 cp ${{ github.workspace }}/mobile-web.zip s3://${{ env.PROD_BUCKET_NAME }}${{ github.repository }}/${{ github.run_number }}/mobile-web.zip
                                                              
