name: Upload to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - dev
      - prod
   
jobs:
 my-job:
   runs-on: ubuntu-latest
   environment: dev
   steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set environment name
        id: set_environment
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/dev' ]]; then
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          elif [[ ${{ github.ref }} == 'refs/heads/prod' ]]; then
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV 
          else
            echo "environment is not specified"
          fi
      - name: Create ZIP file
        run: |
           cd ${{ github.workspace }}
           ls -l
           zip -r ${{ github.workspace }}/mobile-web.zip . -x ./README.md .git\*
      - name: Copy files to S3 (DEV)
        env:
            NAME: ${{ secrets.BUCKET_NAME }}
        run:  aws s3 sync ${{ github.workspace }}/mobile-web.zip s3://$NAME/${{ github.repository }}/${{ github.run_number }}/mobile-web.zip
