name: Upload to S3 and Invalidate CloudFront

on:
  push:
    branches:

      - dev
      - prod
jobs:

 set_environment:

     runs-on: ubuntu-latest
     outputs:
       env_value: ${{ steps.set_env.outputs.environment }}
    
     steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine environment based on branch
        id: set_env
        run: |
          if [ "$GITHUB_REF" == "refs/heads/prod" ]; then
            echo "prod" >> environment
          elif [ "$GITHUB_REF" == "refs/heads/dev" ]; then
            echo "dev" >> environment
          else
            echo "default" >> environment
          fi

 CloudFront_DEPLOY:
 
   runs-on: ubuntu-latest
   env:
      lav: ${{ needs.set_environment.outputs.env_value }}
   environment: "$lav"
   
   steps:

      - name: Checkout repository
        uses: actions/checkout@v2
      - name : Deploy to cloudfront
        env: 
           BUCKET: ${{ secrets.BUCKET_NAME }}
        run: echo $BUCKET
      
