name: Deploy PHP Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      # Add your build and test steps here if needed

      - name: approval
        uses: trstringer/manual-approval@v1
        with:
         secret: ${{ github.TOKEN }}
         approvers: lavanyaprashola
         minimum-approvals: 1
         issue-title: "Deploying v1.3.5 to prod from staging"
         issue-body: "Please approve or deny the deployment of version v1.3.5."
         exclude-workflow-initiator-as-approver: false
         additional-approved-words: 'yes'
         additional-denied-words: 'no'
