name: Deploy PHP Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      # Add your build and test steps here if needed

      - name: Create Manual Approval Request
        uses: repo-sync/pull-request@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          destination_branch: main
          title: "Deploying v1.3.5 to prod from staging"
          body: "Please approve or deny the deployment of version v1.3.5."
